### PR TITLE
A first functional deployment with a single Verifier and Registrar

### PR DESCRIPTION
**Pull request by maugustosilva**
At the moment, just use the `deploy.sh`/`undeploy.sh` scripts, which will create the correct "software bill of materials" (i.e., certificates and environment variables) and ship to kubernetes.

The deployment/service yaml files are being created from a very simple templating mechanism (using sed).

### CODE REVIEW

**Comment by maugustosilva** [comment]
Just for completeness, here is the current "environment file" that I have been using for testing (called by `configmap.sh`):

```
  KEYLIME_AGENT_ENABLE_AGENT_MTLS: "False"
  KEYLIME_AGENT_ENABLE_INSECURE_PAYLOAD: "True"
  KEYLIME_AGENT_TPM_OWNERPASSWORD: ""
  KEYLIME_CA_PASSWORD: "temp4now"
  KEYLIME_LOGGING_LEVEL: "DEBUG"
  KEYLIME_REGISTRAR_IP: "0.0.0.0"
  KEYLIME_REGISTRAR_PORT: "8890"
  KEYLIME_REGISTRAR_TLS_DIR: "default"
  KEYLIME_REGISTRAR_TLS_PORT: "8891"
  KEYLIME_TENANT_ENABLE_AGENT_MTLS: "False"
  KEYLIME_TENANT_REQUIRE_EK_CERT: "True"
  KEYLIME_TENANT_TLS_DIR: "default"
  KEYLIME_TENANT_TPM_CERT_STORE: "/var/lib/keylime/tpm_cert_store/"
  KEYLIME_VERIFIER_ENABLE_AGENT_MTLS: "False"
  KEYLIME_VERIFIER_IP: "0.0.0.0"
  KEYLIME_VERIFIER_MEASURED_BOOT_IMPORTS: "['keylime.mba.elchecking']"
  KEYLIME_VERIFIER_MEASURED_BOOT_POLICY_NAME: "example"
  KEYLIME_VERIFIER_PORT: "8881"
  KEYLIME_VERIFIER_QUOTE_INTERVAL: "5"
  KEYLIME_VERIFIER_TLS_DIR: "generate"
  KEYLIME_VERIFIER_UUID: "verifier0"
```

**Comment by galmasi** [comment]
+1 @maugustosilva I reproduced your setup and got a functional verifier and registrar. Have some issues with the PR which I will comment on separately as Issues, because they are simply not worth stopping the PR.

**Comment by maugustosilva** [comment]
@galmasi @ruocco I believe I've addressed most if not all your concerns. A local Keylime installation is no longer required for deployment on Kubernetes, and neither it is a set of environment variables ("reasonable defaults" are enforced in absence).

**Comment by maugustosilva** [comment]
Fixes #10

**Pull request merged**
